### ISSUE TITLE
Path issue

### ISSUE THREAD

**Issue by capitalkind** [capitalkind/RESTaurantApp#1]
So fortunately changing "groups" to "parties" resolved the fatal issue I was having before, but I still am dealing with something that was a problem all weekend. When I want to make a new order for a party, the only way I'm able to do so is to direct it to the parties/show page, instead of what I would like to do which would be the new/party/order path, any help with this would be great

**Comment by ajhofferber** [comment]
Hey Malcolm, want to try and spike on your issue? I'm out in the lobby.
